sudo: false

cache:
  directories:
    $HOME/.stack

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin/:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - travis_wait stack --no-terminal --install-ghc test --only-dependencies

script:
  - stack --no-terminal --skip-ghc-check test