name:
    valor
version:
    0.1.0.0
github:
    "reygoch/valor"
license:
    MIT
author:
    "Luka Hadžiegrić"
maintainer:
    "reygoch@gmail.com"
copyright:
    "2018 Luka Hadžiegrić"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
    Please see the README on GitHub at <https://github.com/reygoch/valor#readme>

dependencies:
- base >= 4.7 && < 5
- text
- transformers

library:
  source-dirs:
    src

tests:
  valor-test:
    main:
        Spec.hs
    source-dirs:
        test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - valor
    - hspec
    - QuickCheck
    - checkers
    - hspec-checkers